// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-slug/887f85a23a46dcccf69daf033de8c440d2d12b47/slug.d.ts
declare module 'slug' {
function slug (string: string, opts?: 'replacement' | slug.Options): string;

namespace slug {
  export interface Options {
    mode?: string;
    replacement?: string;
    charmap?: CharMap;
    multicharmap?: MultiCharMap;
    remove?: RegExp;
    lower?: boolean;
    symbols?: boolean;
  }

  export interface CharMap {
    [char: string]: string;
  }

  export interface MultiCharMap {
    [string: string]: string;
  }

  export var defaults: {
    mode: string;
    multicharmap: MultiCharMap;
    charmap: CharMap;
    modes: {
      rfc3986: Options;
      pretty: Options;
      [mode: string]: Options;
    };
  };

  export var multicharmap: MultiCharMap;
  export var charmap: CharMap;
}

export = slug;
}
